addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.0")
addSbtPlugin("ch.epfl.scala" % "sbt-version-policy" % "2.1.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.7")
addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.5.3")
addSbtPlugin("ch.epfl.scala" % "sbt-scala3-migrate" % "0.6.1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.13.0")